import pprint
from dotenv import load_dotenv
from .utils import res_to_json,call_model
import uuid
load_dotenv()



def createProblemDescription(blueprint,job_id:int):
    """Creates a problem description"""
    try:
        #pprint.pprint(f"INFO:{blueprint}",indent=4)

        prompt = f"""
You are designing a backend REST API coding challenge.

Goal:
Produce a COMPLETE, UNAMBIGUOUS contract so autogenerated unit tests and a reference implementation ALWAYS behave identically.

Hard rules:
- Output ONLY JSON (no prose, no code, no tests, no tool/library mentions)
- Do NOT assume defaults; undeclared behavior is forbidden
- Path+method pairs must be unique
- Overview ≤ 40 words; behaviour ≤ 20 words
- Invariants must be short and enforceable
- Use ONLY the blueprint fields (do not invent new ones)

Request field requirements (for every field):
type: string|number|integer|boolean
required: true|false
nullable: true|false
allow_empty: true|false
max_length: number|null
Rules:
- Wrong type → 400
- null allowed only if nullable=true
- "" allowed only if allow_empty=true

FINAL OUTPUT RULE:
- Your entire output MUST be exactly one markdown fenced code block
- It MUST start with: ```json
- It MUST end with: ```
- Inside the block must be STRICT JSON (double quotes only, true/false/null only)
- No text before or after the code block

Mandatory consistency:
- Validation happens BEFORE existence/uniqueness checks
- Missing/invalid required fields → 400
- Valid identifiers for missing resources → 404
- Uniqueness violations → 409
- Uniqueness checks run ONLY after validation succeeds, and only on validated non-null fields
- Every status code must match exactly one declared response

Strict error precedence:
1) 400 validation/malformed
2) 404 not found
3) 409 uniqueness
4) success (200 or 201)

Endpoint behavior:
Each endpoint MUST explicitly declare whether it is create, update, or upsert.
- create-only: duplicate → 409
- update-only: missing → 404
- upsert: explicitly declare unique identifier and which fields are overwritten vs preserved

---BLUEPRINT---
{blueprint}
---END BLUEPRINT---

Each endpoint must follow EXACTLY this schema:
{{
  "title": "",
  "overview": "",
  "method": "",
  "path": "",
  "behaviour": "",
  "request": {{
    "field_name": {{
      "type": "",
      "required": true,
      "nullable": false,
      "allow_empty": false,
      "max_length": null
    }}
  }},
  "responses": {{ "200": "", "201": "", "400": "", "404": "", "409": "" }},
  "invariants": []
}}

Output JSON ONLY in this structure:
```json
{{
  "title": "",
  "overview": "",
  "endpoints": [],
  "notes": []
}}
```
"""

        response = call_model(prompt,useCase="problem",job_id=job_id)
        json_res = res_to_json(response.text)
        json_res["id"] = str(uuid.uuid4())
        json_res['difficulty'] = blueprint.get('difficulty')
        return json_res
    except Exception as e:
        print(f"ERROR: During generation of problem description {str(e)}")
        raise

if __name__ == "__main__":
    res = createProblemDescription()
    pprint.pprint(res,indent=4)